image: java-latest

stages:
  - build
  - test
  - package
  - deploy

build:
  stage: build
  tags:
    - ugrad
  script:
    - "mvn compile"
  only:
    - production

test:
  stage: test
  tags:
    - ugrad
  script:
    - "mvn clean test"
  artifacts:
    paths:
      - "./target/surefire-reports/TEST-*.xml"
    reports:
      junit:
        - "./target/surefire-reports/TEST-*.xml"
  only:
    - production
package:
  stage: package
  tags:
    - ugrad
  script:
    - "mvn package"
  artifacts:
    when: on_success
    paths:
      - target/*.jar
  only:
    - production
deploy:
  stage: deploy
  only:
    - production
  image: ruby:latest
  tags:
    - ugrad
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
  script:
    - echo "mysqlJDBCDriver=com.mysql.cj.jdbc.Driver" >> database.properties
    - echo "databaseType=prod" >> database.properties
    - echo "databaseURL=$PROD_DATABASE_URL" >> database.properties
    - echo "prodDatabase=$PROD_DATABASE" >> databaseConfig.properties
    - echo "prodUsername=$PROD_DATABASE_USERNAME" >> database.properties
    - echo "prodPassword=$PROD_DATABASE_PASSWORD" >> database.properties
    - ssh -o StrictHostKeyChecking=no manikandan@timberlea.cs.dal.ca "mkdir production/${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}"
    - scp -r -o StrictHostKeyChecking=no target/group-9-1.0.0.jar "manikandan@timberlea.cs.dal.ca:production/${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}/group-9-1.0.0.jar"
    - scp -r -o StrictHostKeyChecking=no database.properties "manikandan@timberlea.cs.dal.ca:production/${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}/database.properties"
