package edu.dalhousie.business.addnewapplication.constants;

public class StringConstants {
    public static String kAddNewApplication = "AddNewApplicationForAdmission";
    public static String kFeedbackMenu = "FeedbackMenu";
    public static String kRoommateFinder = "RoommateFinder";
    public static String kFirstQuestion = "Enter your preferred course name";
    public static String kSecondQuestion = "Enter your previous university/College name";
    public static String kThirdQuestion = "Enter your previous level of education: (1: Diploma, 2: UG, 3:PG, 4:PHD)";
    public static String kFourthQuestion = "Enter your CGPA";
    public static String kFifthQuestion = "Enter your 10th percentage";
    public static String kSixthQuestion = "Enter your 12th percentage";
    public static String kSeventhQuestion = "Enter your IELTS";
    public static String kEigthQuestion = "Enter your GRE";
    public static String kNinethQuestion = "Enter the number of research publications you have published";
    public static String kTenthQuestion = "Enter work experience in years: (If any else enter 0)";
    public static String kEleventhQuestion = "Enter your GMAT score: (If any else enter 0)";
    public static String kTwelfthQuestion = "Enter your GATE score: (If any else enter 0)";
    public static String kCalculationInProgress = "Calculation in progress...";
    public static String kResultWillBeShownInSometime = "Result will be shown in sometime...";
    public static String kDecision = "Decision: ";
    public static String kSuccess = "Success";
    public static String kValidCourse = "Please enter valid course name";
    public static String kValidPreviousSchoolName = "Please enter valid previous university/school name";
    public static String kOnlyOneEducation = "Please enter only one education";
    public static String kCGPAInNumericsOnly = "Please enter cgpa in numerics only";
    public static String kValidCGPA = "Please enter valid cgpa";
    public static String kValidPreviousLevelOfEducation = "Please enter valid previous level of education";
    public static String kValidTenthPercentage = "Please enter valid Tenth Percentage";
    public static String kPercentageInNumericsOnly = "Please do not type '%'. Enter in numerics only";
    public static String kTenthPercentageInNumericsOnly = "Please enter tenth percentage in numerics only";
    public static String kTwelfthPercentageInNumericsOnly = "Please enter twelfth percentage in numerics only";
    public static String kValidTwelfthPercentage = "Please enter valid twelfth percentage";
    public static String kIIT = "iit";
    public static String kIndianInstituteOfTechnology = "indian institute of technology";
    public static String kNIT = "nit";
    public static String kNationalInstituteOfTechnology = "national institute of technology";
    public static String kApplicationApproved = "Congratulations! You're application is approved.";
    public static String kApplicationDenied = "Sorry, you're application has been denied.";
}
